version: "3.8"
services:
  chrome:
    container_name: chrome
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  warcdriver:
    container_name: warcdriver
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    restart: unless-stopped
    volumes:
      - ./data:/data
    depends_on:
      - chrome
    networks:
      - default
    expose:
       - "8808"
    ports:
      - 8808:8808
