// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes    = "bearerAuth.Scopes"
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for ArchiveScope.
const (
	ExplicitUrls  ArchiveScope = "explicit_urls"
	LinkedPages   ArchiveScope = "linked_pages"
	Prefix        ArchiveScope = "prefix"
	SameSubdomain ArchiveScope = "same_subdomain"
	SinglePage    ArchiveScope = "single_page"
)

// Defines values for CookieProfileSourceType.
const (
	Json      CookieProfileSourceType = "json"
	Netscape  CookieProfileSourceType = "netscape"
	RawHeader CookieProfileSourceType = "raw_header"
)

// Defines values for JobStatus.
const (
	Canceled  JobStatus = "canceled"
	Failed    JobStatus = "failed"
	Queued    JobStatus = "queued"
	Running   JobStatus = "running"
	Succeeded JobStatus = "succeeded"
)

// ArchiveJob defines model for ArchiveJob.
type ArchiveJob struct {
	CaptureId     *string      `json:"captureId,omitempty"`
	CreatedAt     time.Time    `json:"createdAt"`
	Depth         int          `json:"depth"`
	Error         *string      `json:"error,omitempty"`
	FinishedAt    *time.Time   `json:"finishedAt,omitempty"`
	Id            string       `json:"id"`
	MaxPages      int          `json:"maxPages"`
	Scope         ArchiveScope `json:"scope"`
	StartedAt     *time.Time   `json:"startedAt,omitempty"`
	Status        JobStatus    `json:"status"`
	StatusMessage *string      `json:"statusMessage,omitempty"`
	Url           string       `json:"url"`
}

// ArchiveJobDetail defines model for ArchiveJobDetail.
type ArchiveJobDetail struct {
	CaptureId     *string      `json:"captureId,omitempty"`
	CreatedAt     time.Time    `json:"createdAt"`
	Depth         int          `json:"depth"`
	Error         *string      `json:"error,omitempty"`
	FinishedAt    *time.Time   `json:"finishedAt,omitempty"`
	Id            string       `json:"id"`
	Items         *[]Item      `json:"items,omitempty"`
	Logs          []JobLog     `json:"logs"`
	MaxPages      int          `json:"maxPages"`
	Scope         ArchiveScope `json:"scope"`
	StartedAt     *time.Time   `json:"startedAt,omitempty"`
	Status        JobStatus    `json:"status"`
	StatusMessage *string      `json:"statusMessage,omitempty"`
	Url           string       `json:"url"`
}

// ArchiveScope defines model for ArchiveScope.
type ArchiveScope string

// CookieProfile defines model for CookieProfile.
type CookieProfile struct {
	CreatedAt  time.Time               `json:"createdAt"`
	Host       *string                 `json:"host,omitempty"`
	Id         string                  `json:"id"`
	Name       string                  `json:"name"`
	SourceType CookieProfileSourceType `json:"sourceType"`
}

// CookieProfileSourceType defines model for CookieProfileSourceType.
type CookieProfileSourceType string

// CreateArchiveJobRequest defines model for CreateArchiveJobRequest.
type CreateArchiveJobRequest struct {
	CookieProfileId *string       `json:"cookieProfileId,omitempty"`
	Depth           *int          `json:"depth,omitempty"`
	Enrich          *bool         `json:"enrich,omitempty"`
	MaxPages        *int          `json:"maxPages,omitempty"`
	Prefix          *string       `json:"prefix,omitempty"`
	Scope           *ArchiveScope `json:"scope,omitempty"`
	Url             string        `json:"url"`
	Urls            *[]string     `json:"urls,omitempty"`
}

// CreateCookieProfileRequest defines model for CreateCookieProfileRequest.
type CreateCookieProfileRequest struct {
	Content      *string                 `json:"content,omitempty"`
	CookieHeader *string                 `json:"cookieHeader,omitempty"`
	Host         *string                 `json:"host,omitempty"`
	Name         string                  `json:"name"`
	SourceType   CookieProfileSourceType `json:"sourceType"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Item defines model for Item.
type Item struct {
	CanonicalUrl *string   `json:"canonicalUrl,omitempty"`
	CaptureId    string    `json:"captureId"`
	ContentType  *string   `json:"contentType,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
	Depth        int       `json:"depth"`
	Id           string    `json:"id"`
	SiteId       string    `json:"siteId"`
	StatusCode   *int      `json:"statusCode,omitempty"`
	Summary      *string   `json:"summary,omitempty"`
	Tags         *[]string `json:"tags,omitempty"`
	Title        string    `json:"title"`
	Url          string    `json:"url"`
}

// ItemDetail defines model for ItemDetail.
type ItemDetail struct {
	CanonicalUrl    *string   `json:"canonicalUrl,omitempty"`
	CaptureId       string    `json:"captureId"`
	ContentType     *string   `json:"contentType,omitempty"`
	CreatedAt       time.Time `json:"createdAt"`
	Depth           int       `json:"depth"`
	Id              string    `json:"id"`
	Markdown        *string   `json:"markdown,omitempty"`
	ReplayUrl       *string   `json:"replayUrl,omitempty"`
	SiteId          string    `json:"siteId"`
	StatusCode      *int      `json:"statusCode,omitempty"`
	Summary         *string   `json:"summary,omitempty"`
	Tags            *[]string `json:"tags,omitempty"`
	Title           string    `json:"title"`
	Url             string    `json:"url"`
	WarcDownloadUrl *string   `json:"warcDownloadUrl,omitempty"`
}

// JobLog defines model for JobLog.
type JobLog struct {
	At      time.Time `json:"at"`
	Level   string    `json:"level"`
	Message string    `json:"message"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	User User `json:"user"`
}

// Settings defines model for Settings.
type Settings struct {
	EnrichmentEnabled          bool     `json:"enrichmentEnabled"`
	FilterLists                []string `json:"filterLists"`
	OpenRouterApiKeyConfigured *bool    `json:"openRouterApiKeyConfigured,omitempty"`
	OpenRouterModel            string   `json:"openRouterModel"`
	UserAgent                  *string  `json:"userAgent,omitempty"`
}

// Site defines model for Site.
type Site struct {
	CreatedAt time.Time `json:"createdAt"`
	Host      string    `json:"host"`
	Id        string    `json:"id"`
	ItemCount int       `json:"itemCount"`
	Title     *string   `json:"title,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// SiteDetail defines model for SiteDetail.
type SiteDetail struct {
	Items []Item `json:"items"`
	Site  Site   `json:"site"`
}

// UpdateSettingsRequest defines model for UpdateSettingsRequest.
type UpdateSettingsRequest struct {
	EnrichmentEnabled *bool     `json:"enrichmentEnabled,omitempty"`
	FilterLists       *[]string `json:"filterLists,omitempty"`
	OpenRouterApiKey  *string   `json:"openRouterApiKey,omitempty"`
	OpenRouterModel   *string   `json:"openRouterModel,omitempty"`
	UserAgent         *string   `json:"userAgent,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time `json:"createdAt"`
	DisplayName string    `json:"displayName"`
	Email       *string   `json:"email,omitempty"`
	Id          string    `json:"id"`
	Username    string    `json:"username"`
}

// WarcMetadata defines model for WarcMetadata.
type WarcMetadata struct {
	CaptureId string    `json:"captureId"`
	CreatedAt time.Time `json:"createdAt"`
	StartUrl  string    `json:"startUrl"`
	Title     *string   `json:"title,omitempty"`
}

// Id defines model for Id.
type Id = string

// Error defines model for Error.
type Error = ErrorResponse

// ListArchiveJobsParams defines parameters for ListArchiveJobs.
type ListArchiveJobsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	SiteId *string `form:"siteId,omitempty" json:"siteId,omitempty"`
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSitesParams defines parameters for ListSites.
type ListSitesParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateArchiveJobJSONRequestBody defines body for CreateArchiveJob for application/json ContentType.
type CreateArchiveJobJSONRequestBody = CreateArchiveJobRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateCookieProfileJSONRequestBody defines body for CreateCookieProfile for application/json ContentType.
type CreateCookieProfileJSONRequestBody = CreateCookieProfileRequest

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = UpdateSettingsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/archive-jobs)
	ListArchiveJobs(w http.ResponseWriter, r *http.Request, params ListArchiveJobsParams)

	// (POST /api/archive-jobs)
	CreateArchiveJob(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/archive-jobs/{id})
	DeleteArchiveJob(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/archive-jobs/{id})
	GetArchiveJob(w http.ResponseWriter, r *http.Request, id Id)

	// (POST /api/archive-jobs/{id}/cancel)
	CancelArchiveJob(w http.ResponseWriter, r *http.Request, id Id)

	// (POST /api/auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /api/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (GET /api/cookie-profiles)
	ListCookieProfiles(w http.ResponseWriter, r *http.Request)

	// (POST /api/cookie-profiles)
	CreateCookieProfile(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/cookie-profiles/{id})
	DeleteCookieProfile(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/items)
	ListItems(w http.ResponseWriter, r *http.Request, params ListItemsParams)

	// (DELETE /api/items/{id})
	DeleteItem(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/items/{id})
	GetItem(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (GET /api/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)

	// (PUT /api/settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)

	// (POST /api/settings/openrouter/test)
	TestOpenRouter(w http.ResponseWriter, r *http.Request)

	// (GET /api/sites)
	ListSites(w http.ResponseWriter, r *http.Request, params ListSitesParams)

	// (DELETE /api/sites/{id})
	DeleteSite(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/sites/{id})
	GetSite(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/warcs/{id}/download)
	DownloadWarc(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/warcs/{id}/metadata)
	GetWarcMetadata(w http.ResponseWriter, r *http.Request, id Id)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/archive-jobs)
func (_ Unimplemented) ListArchiveJobs(w http.ResponseWriter, r *http.Request, params ListArchiveJobsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/archive-jobs)
func (_ Unimplemented) CreateArchiveJob(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/archive-jobs/{id})
func (_ Unimplemented) DeleteArchiveJob(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/archive-jobs/{id})
func (_ Unimplemented) GetArchiveJob(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/archive-jobs/{id}/cancel)
func (_ Unimplemented) CancelArchiveJob(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/cookie-profiles)
func (_ Unimplemented) ListCookieProfiles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/cookie-profiles)
func (_ Unimplemented) CreateCookieProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/cookie-profiles/{id})
func (_ Unimplemented) DeleteCookieProfile(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/items)
func (_ Unimplemented) ListItems(w http.ResponseWriter, r *http.Request, params ListItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/items/{id})
func (_ Unimplemented) DeleteItem(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/items/{id})
func (_ Unimplemented) GetItem(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/settings)
func (_ Unimplemented) UpdateSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/settings/openrouter/test)
func (_ Unimplemented) TestOpenRouter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/sites)
func (_ Unimplemented) ListSites(w http.ResponseWriter, r *http.Request, params ListSitesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/sites/{id})
func (_ Unimplemented) DeleteSite(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/sites/{id})
func (_ Unimplemented) GetSite(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/warcs/{id}/download)
func (_ Unimplemented) DownloadWarc(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/warcs/{id}/metadata)
func (_ Unimplemented) GetWarcMetadata(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListArchiveJobs operation middleware
func (siw *ServerInterfaceWrapper) ListArchiveJobs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListArchiveJobsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArchiveJobs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateArchiveJob operation middleware
func (siw *ServerInterfaceWrapper) CreateArchiveJob(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateArchiveJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArchiveJob operation middleware
func (siw *ServerInterfaceWrapper) DeleteArchiveJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArchiveJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArchiveJob operation middleware
func (siw *ServerInterfaceWrapper) GetArchiveJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArchiveJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelArchiveJob operation middleware
func (siw *ServerInterfaceWrapper) CancelArchiveJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelArchiveJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCookieProfiles operation middleware
func (siw *ServerInterfaceWrapper) ListCookieProfiles(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCookieProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCookieProfile operation middleware
func (siw *ServerInterfaceWrapper) CreateCookieProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCookieProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCookieProfile operation middleware
func (siw *ServerInterfaceWrapper) DeleteCookieProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCookieProfile(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "siteId" -------------

	err = runtime.BindQueryParameter("form", true, false, "siteId", r.URL.Query(), &params.SiteId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "siteId", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestOpenRouter operation middleware
func (siw *ServerInterfaceWrapper) TestOpenRouter(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestOpenRouter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSites operation middleware
func (siw *ServerInterfaceWrapper) ListSites(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSitesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSites(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSite operation middleware
func (siw *ServerInterfaceWrapper) DeleteSite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSite operation middleware
func (siw *ServerInterfaceWrapper) GetSite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadWarc operation middleware
func (siw *ServerInterfaceWrapper) DownloadWarc(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadWarc(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWarcMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetWarcMetadata(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWarcMetadata(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/archive-jobs", wrapper.ListArchiveJobs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/archive-jobs", wrapper.CreateArchiveJob)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/archive-jobs/{id}", wrapper.DeleteArchiveJob)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/archive-jobs/{id}", wrapper.GetArchiveJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/archive-jobs/{id}/cancel", wrapper.CancelArchiveJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/cookie-profiles", wrapper.ListCookieProfiles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/cookie-profiles", wrapper.CreateCookieProfile)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/cookie-profiles/{id}", wrapper.DeleteCookieProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/items", wrapper.ListItems)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/items/{id}", wrapper.DeleteItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/items/{id}", wrapper.GetItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/settings", wrapper.UpdateSettings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/settings/openrouter/test", wrapper.TestOpenRouter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sites", wrapper.ListSites)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/sites/{id}", wrapper.DeleteSite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sites/{id}", wrapper.GetSite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/warcs/{id}/download", wrapper.DownloadWarc)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/warcs/{id}/metadata", wrapper.GetWarcMetadata)
	})

	return r
}
